[package]
name = "battleship"
version = "0.1.0"
edition = "2021"
authors = ["Felix Jablinski"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
